//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int ReservationId { get; set; }
        public int HomeId { get; set; }
        public int LocationId { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public Nullable<int> ServiceId { get; set; }
    
        public virtual Homes Homes { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Services Services { get; set; }
    }
}
